# Site settings
title: Paul's Jekyll Blog!
author:
  name: Paul Anthony Middleton
  email: https://twitter.com/paulonjog
description: "My first site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima
